application: fourtune-cookie1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static/css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /static/html/(.*\.html)
  mime_type: text/html
  static_files: static/html/\1
  upload: static/(.*\.html)

- url: /static/js/(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/js/(.*\.js)

- url: /static/txt/(.*\.txt)
  mime_type: text/plain
  static_files: static/txt/\1
  upload: static/txt/(.*\.txt)

- url: /static/xml/(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/xml/(.*\.xml)

# image files
- url: /static/imaages/(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/images/\1
  upload: static/images/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# index files
- url: /static/html/(.+)/
  static_files: static/\1/index.html
  upload: static/html/(.+)/index.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
